FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True
SECRET_KEY = "pk.eyJ1IjoiY3VuZ3Ryb25naGF1IiwiYSI6ImNscW8yaGFhYzJxdzkycXM1bzNrM2g1d2EifQ.pH2BfbOJ-tHeOWEWqF3yLg"
MAPBOX_API_KEY = 'pk.eyJ1IjoiY3VuZ3Ryb25naGF1IiwiYSI6ImNscW8yaGFhYzJxdzkycXM1bzNrM2g1d2EifQ.pH2BfbOJ-tHeOWEWqF3yLg'